-- 코드를 입력하세요 총 거래금액 이기 때문에
SELECT
    u.USER_ID,
    u.NICKNAME,
    sum(b.PRICE) AS 'TOTAL_SALES'
FROM USED_GOODS_USER u
JOIN USED_GOODS_BOARD b ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY u.USER_ID
HAVING sum(b.PRICE) >= 700000
ORDER BY sum(b.PRICE) ASC